spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chmedt?serverTimezone=UTC
    username: root
    password: 9527
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    cache: false


